"""Seed dataset — top ~12 players per team for all 48 World Cup nations.

These ratings approximate FIFA-style overall scores (~60 to ~91) based on
2025/26 club season form and international form, current to late 2025.
They are deliberately top-heavy — these are the players most likely to
actually appear in a squad and matter for predictions.

You can edit this file to update ratings before re-deploying, or use the
in-app Override UI to adjust without touching code.
"""

from __future__ import annotations

# Schema: (name, position, rating, age, club)
SEED_PLAYERS: dict[str, list[tuple[str, str, int, int, str]]] = {
    # ===== Group A =====
    "Mexico": [
        ("Edson Álvarez", "MID", 82, 28, "Fenerbahçe"),
        ("Hirving Lozano", "FWD", 80, 30, "San Diego FC"),
        ("Raúl Jiménez", "FWD", 79, 34, "Fulham"),
        ("Santiago Giménez", "FWD", 81, 25, "AC Milan"),
        ("Luis Romo", "MID", 78, 30, "Cruz Azul"),
        ("Orbelín Pineda", "MID", 77, 30, "AEK Athens"),
        ("César Montes", "DEF", 78, 28, "Lokomotiv Moscow"),
        ("Johan Vásquez", "DEF", 78, 27, "Genoa"),
        ("Jesús Gallardo", "DEF", 76, 31, "Toluca"),
        ("Jorge Sánchez", "DEF", 75, 28, "Cruz Azul"),
        ("Guillermo Ochoa", "GK", 79, 40, "AVS"),
        ("Luis Malagón", "GK", 77, 28, "América"),
    ],
    "South Korea": [
        ("Son Heung-min", "FWD", 86, 33, "LAFC"),
        ("Lee Kang-in", "MID", 83, 24, "PSG"),
        ("Kim Min-jae", "DEF", 86, 29, "Bayern Munich"),
        ("Hwang Hee-chan", "FWD", 80, 29, "Wolves"),
        ("Hwang In-beom", "MID", 79, 29, "Feyenoord"),
        ("Lee Jae-sung", "MID", 78, 33, "Mainz"),
        ("Jung Woo-young", "MID", 76, 36, "Al-Khalij"),
        ("Bae Jun-ho", "FWD", 76, 22, "Stoke City"),
        ("Kim Young-gwon", "DEF", 78, 36, "Ulsan"),
        ("Seol Young-woo", "DEF", 76, 27, "Ulsan"),
        ("Kim Jin-su", "DEF", 76, 33, "Al-Ettifaq"),
        ("Kim Seung-gyu", "GK", 78, 35, "Al-Shabab"),
    ],
    "South Africa": [
        ("Lyle Foster", "FWD", 76, 25, "Burnley"),
        ("Percy Tau", "FWD", 75, 31, "Qatar SC"),
        ("Themba Zwane", "MID", 77, 36, "Mamelodi Sundowns"),
        ("Teboho Mokoena", "MID", 77, 28, "Mamelodi Sundowns"),
        ("Mihlali Mayambela", "FWD", 73, 29, "Aris Limassol"),
        ("Mothobi Mvala", "MID", 73, 31, "Mamelodi Sundowns"),
        ("Siyanda Xulu", "DEF", 73, 33, "Sekhukhune United"),
        ("Mbekezeli Mbokazi", "DEF", 74, 20, "Orlando Pirates"),
        ("Nkosinathi Sibisi", "DEF", 73, 28, "Orlando Pirates"),
        ("Aubrey Modiba", "DEF", 74, 30, "Mamelodi Sundowns"),
        ("Ronwen Williams", "GK", 80, 33, "Mamelodi Sundowns"),
        ("Bathusi Aubaas", "MID", 73, 23, "Mamelodi Sundowns"),
    ],
    "Czech Republic": [
        ("Patrik Schick", "FWD", 81, 30, "Bayer Leverkusen"),
        ("Tomáš Souček", "MID", 79, 31, "West Ham"),
        ("Adam Hložek", "FWD", 78, 23, "Hoffenheim"),
        ("Mojmír Chytil", "FWD", 75, 26, "Plzeň"),
        ("Lukáš Provod", "MID", 76, 29, "Slavia Praha"),
        ("Pavel Šulc", "MID", 78, 25, "Lyon"),
        ("Antonín Barák", "MID", 78, 31, "Kasimpasa"),
        ("Tomáš Holeš", "MID", 76, 32, "Slavia Praha"),
        ("Vladimír Coufal", "DEF", 77, 33, "Hoffenheim"),
        ("David Jurásek", "DEF", 75, 24, "Hoffenheim"),
        ("David Doudera", "DEF", 74, 27, "Slavia Praha"),
        ("Jindřich Staněk", "GK", 78, 29, "Slavia Praha"),
    ],
    # ===== Group B =====
    "Canada": [
        ("Alphonso Davies", "DEF", 86, 25, "Real Madrid"),
        ("Jonathan David", "FWD", 84, 26, "Juventus"),
        ("Stephen Eustáquio", "MID", 80, 29, "Porto"),
        ("Cyle Larin", "FWD", 78, 30, "Mallorca"),
        ("Tajon Buchanan", "MID", 79, 26, "Inter"),
        ("Ismaël Koné", "MID", 77, 23, "Sassuolo"),
        ("Moïse Bombito", "DEF", 77, 25, "Nice"),
        ("Derek Cornelius", "DEF", 75, 28, "Marseille"),
        ("Alistair Johnston", "DEF", 79, 27, "Celtic"),
        ("Richie Laryea", "DEF", 73, 31, "Toronto FC"),
        ("Maxime Crépeau", "GK", 76, 31, "LAFC"),
        ("Dayne St. Clair", "GK", 75, 28, "Minnesota United"),
    ],
    "Switzerland": [
        ("Granit Xhaka", "MID", 82, 33, "Sunderland"),
        ("Manuel Akanji", "DEF", 83, 30, "Inter"),
        ("Breel Embolo", "FWD", 79, 28, "Rennes"),
        ("Xherdan Shaqiri", "MID", 78, 34, "Chicago Fire"),
        ("Ricardo Rodríguez", "DEF", 78, 33, "Real Betis"),
        ("Remo Freuler", "MID", 79, 33, "Bologna"),
        ("Fabian Rieder", "MID", 76, 23, "Stuttgart"),
        ("Dan Ndoye", "FWD", 80, 25, "Nottingham Forest"),
        ("Nico Elvedi", "DEF", 79, 29, "Borussia Mönchengladbach"),
        ("Silvan Widmer", "DEF", 76, 32, "Mainz"),
        ("Zeki Amdouni", "FWD", 77, 25, "Benfica"),
        ("Yann Sommer", "GK", 83, 37, "Inter"),
    ],
    "Qatar": [
        ("Akram Afif", "FWD", 81, 29, "Al-Sadd"),
        ("Almoez Ali", "FWD", 78, 29, "Al-Duhail"),
        ("Hassan Al-Haydos", "MID", 76, 34, "Al-Sadd"),
        ("Ismail Mohamad", "DEF", 75, 35, "Al-Duhail"),
        ("Boualem Khoukhi", "DEF", 75, 35, "Al-Ahli"),
        ("Tarek Salman", "DEF", 75, 28, "Al-Sadd"),
        ("Bassam Al-Rawi", "DEF", 74, 28, "Al-Duhail"),
        ("Karim Boudiaf", "MID", 75, 35, "Al-Duhail"),
        ("Abdulaziz Hatem", "MID", 74, 35, "Al-Rayyan"),
        ("Hatem Abdelaziz", "MID", 73, 29, "Al-Sadd"),
        ("Mostafa Mashaal", "MID", 72, 28, "Al-Sadd"),
        ("Saad Al-Sheeb", "GK", 76, 35, "Al-Sadd"),
    ],
    "Bosnia and Herzegovina": [
        ("Edin Džeko", "FWD", 80, 39, "Fiorentina"),
        ("Sead Kolašinac", "DEF", 77, 32, "Atalanta"),
        ("Miralem Pjanić", "MID", 78, 35, "CSKA 1948"),
        ("Edin Višća", "FWD", 76, 35, "Trabzonspor"),
        ("Smail Prevljak", "FWD", 75, 30, "Mechelen"),
        ("Ermedin Demirović", "FWD", 78, 27, "Stuttgart"),
        ("Nihad Mujakić", "DEF", 75, 26, "Rizespor"),
        ("Amar Dedić", "DEF", 78, 23, "Benfica"),
        ("Sanjin Prcić", "MID", 76, 31, "Strasbourg"),
        ("Benjamin Tahirović", "MID", 75, 22, "Roma"),
        ("Haris Hajradinović", "MID", 75, 31, "Kasimpasa"),
        ("Nikola Vasilj", "GK", 76, 29, "St. Pauli"),
    ],
    # ===== Group C =====
    "Brazil": [
        ("Vinícius Júnior", "FWD", 89, 25, "Real Madrid"),
        ("Rodrygo", "FWD", 85, 25, "Real Madrid"),
        ("Raphinha", "FWD", 87, 28, "Barcelona"),
        ("Neymar Jr", "FWD", 83, 33, "Santos"),
        ("Bruno Guimarães", "MID", 84, 28, "Newcastle"),
        ("Lucas Paquetá", "MID", 82, 28, "West Ham"),
        ("Casemiro", "MID", 82, 33, "Man United"),
        ("Marquinhos", "DEF", 85, 31, "PSG"),
        ("Gabriel Magalhães", "DEF", 85, 28, "Arsenal"),
        ("Éder Militão", "DEF", 84, 27, "Real Madrid"),
        ("Vanderson", "DEF", 79, 24, "Monaco"),
        ("Alisson Becker", "GK", 88, 33, "Liverpool"),
    ],
    "Morocco": [
        ("Achraf Hakimi", "DEF", 88, 27, "PSG"),
        ("Hakim Ziyech", "MID", 81, 32, "Al Duhail"),
        ("Sofyan Amrabat", "MID", 81, 29, "Real Betis"),
        ("Brahim Díaz", "MID", 83, 26, "Real Madrid"),
        ("Youssef En-Nesyri", "FWD", 82, 28, "Fenerbahçe"),
        ("Azzedine Ounahi", "MID", 79, 25, "Olympiacos"),
        ("Bilal El Khannouss", "MID", 79, 21, "Stuttgart"),
        ("Ayoub El Kaabi", "FWD", 80, 32, "Olympiacos"),
        ("Romain Saïss", "DEF", 79, 35, "Al Shamal"),
        ("Noussair Mazraoui", "DEF", 81, 28, "Man United"),
        ("Nayef Aguerd", "DEF", 81, 29, "Real Sociedad"),
        ("Yassine Bounou", "GK", 84, 34, "Al-Hilal"),
    ],
    "Haiti": [
        ("Frantzdy Pierrot", "FWD", 75, 30, "Riga FC"),
        ("Duckens Nazon", "FWD", 73, 31, "Persikabo"),
        ("Danley Jean Jacques", "MID", 74, 25, "Lokomotiva"),
        ("Carl Sainté", "MID", 73, 28, "AS Monaco II"),
        ("Lugentz Cinéus", "DEF", 73, 25, "Hapoel Be'er Sheva"),
        ("Ricardo Adé", "DEF", 75, 25, "Sheffield Wednesday"),
        ("Garven Metusala", "DEF", 72, 26, "Real Hope"),
        ("Caleb Shaeem", "MID", 72, 23, "Real Hope"),
        ("Kervens Belfort", "FWD", 72, 27, "Persikabo"),
        ("Steeven Saba", "MID", 72, 26, "Heart of Lions"),
        ("Don Anderson Deedson", "DEF", 71, 24, "Real Hope"),
        ("Johny Placide", "GK", 74, 36, "USL Dunkerque"),
    ],
    "Scotland": [
        ("Andy Robertson", "DEF", 84, 31, "Liverpool"),
        ("Scott McTominay", "MID", 84, 28, "Napoli"),
        ("John McGinn", "MID", 80, 31, "Aston Villa"),
        ("Kieran Tierney", "DEF", 80, 28, "Celtic"),
        ("Ben Doak", "FWD", 78, 20, "Bournemouth"),
        ("Lewis Ferguson", "MID", 79, 26, "Bologna"),
        ("Billy Gilmour", "MID", 79, 24, "Napoli"),
        ("Jack Hendry", "DEF", 76, 30, "Al-Ettifaq"),
        ("Lawrence Shankland", "FWD", 76, 30, "Hearts"),
        ("Che Adams", "FWD", 78, 29, "Torino"),
        ("Aaron Hickey", "DEF", 77, 23, "Brentford"),
        ("Angus Gunn", "GK", 78, 30, "Stade Nyonnais"),
    ],
    # ===== Group D =====
    "United States": [
        ("Christian Pulisic", "FWD", 85, 27, "AC Milan"),
        ("Weston McKennie", "MID", 80, 27, "Juventus"),
        ("Tyler Adams", "MID", 80, 27, "Bournemouth"),
        ("Yunus Musah", "MID", 79, 23, "AC Milan"),
        ("Gio Reyna", "MID", 78, 23, "Borussia Mönchengladbach"),
        ("Folarin Balogun", "FWD", 79, 24, "Monaco"),
        ("Timothy Weah", "FWD", 78, 25, "Juventus"),
        ("Antonee Robinson", "DEF", 81, 28, "Fulham"),
        ("Sergiño Dest", "DEF", 78, 25, "PSV"),
        ("Chris Richards", "DEF", 79, 25, "Crystal Palace"),
        ("Tim Ream", "DEF", 76, 38, "Charlotte FC"),
        ("Matt Turner", "GK", 78, 31, "Crystal Palace"),
    ],
    "Paraguay": [
        ("Miguel Almirón", "FWD", 78, 31, "Atlanta United"),
        ("Antonio Sanabria", "FWD", 77, 29, "Cremonese"),
        ("Damián Bobadilla", "MID", 75, 24, "São Paulo"),
        ("Diego Gómez", "MID", 78, 22, "Brighton"),
        ("Andrés Cubas", "MID", 75, 29, "Vancouver"),
        ("Mathías Villasanti", "MID", 74, 27, "Grêmio"),
        ("Gustavo Velázquez", "DEF", 73, 24, "Cerro Porteño"),
        ("Junior Alonso", "DEF", 75, 32, "Boca Juniors"),
        ("Omar Alderete", "DEF", 76, 28, "Getafe"),
        ("Damián Martínez", "DEF", 72, 27, "Libertad"),
        ("Julio Enciso", "FWD", 78, 21, "Ipswich Town"),
        ("Antony Silva", "GK", 73, 41, "Olimpia"),
    ],
    "Australia": [
        ("Mathew Ryan", "GK", 78, 33, "AS Roma"),
        ("Aiden O'Neill", "MID", 73, 27, "Standard Liège"),
        ("Mitchell Duke", "FWD", 73, 34, "Machida Zelvia"),
        ("Jackson Irvine", "MID", 75, 32, "St. Pauli"),
        ("Awer Mabil", "FWD", 73, 30, "Grasshopper"),
        ("Riley McGree", "MID", 74, 26, "Middlesbrough"),
        ("Cameron Burgess", "DEF", 72, 30, "Ipswich Town"),
        ("Harry Souttar", "DEF", 76, 27, "Sheffield United"),
        ("Kye Rowles", "DEF", 73, 27, "Heart of Midlothian"),
        ("Jordan Bos", "DEF", 73, 23, "Westerlo"),
        ("Connor Metcalfe", "MID", 73, 26, "St. Pauli"),
        ("Sammy Silvera", "FWD", 71, 25, "Middlesbrough"),
    ],
    "Turkey": [
        ("Hakan Çalhanoğlu", "MID", 86, 31, "Inter"),
        ("Arda Güler", "MID", 84, 20, "Real Madrid"),
        ("Kenan Yıldız", "FWD", 83, 20, "Juventus"),
        ("Cengiz Ünder", "FWD", 79, 28, "Fenerbahçe"),
        ("İrfan Can Kahveci", "MID", 79, 30, "Fenerbahçe"),
        ("Orkun Kökçü", "MID", 81, 24, "Benfica"),
        ("Mert Müldür", "DEF", 78, 26, "Fenerbahçe"),
        ("Merih Demiral", "DEF", 80, 27, "Al-Ahli"),
        ("Çağlar Söyüncü", "DEF", 78, 29, "Fenerbahçe"),
        ("Ferdi Kadıoğlu", "DEF", 81, 26, "Brighton"),
        ("Salih Özcan", "MID", 78, 27, "VfB Stuttgart"),
        ("Mert Günok", "GK", 79, 36, "Beşiktaş"),
    ],
    # ===== Group E =====
    "Germany": [
        ("Florian Wirtz", "MID", 88, 22, "Liverpool"),
        ("Jamal Musiala", "MID", 88, 22, "Bayern Munich"),
        ("Kai Havertz", "FWD", 84, 26, "Arsenal"),
        ("Leroy Sané", "FWD", 83, 29, "Galatasaray"),
        ("Serge Gnabry", "FWD", 82, 30, "Bayern Munich"),
        ("İlkay Gündoğan", "MID", 82, 35, "Galatasaray"),
        ("Joshua Kimmich", "MID", 86, 30, "Bayern Munich"),
        ("Antonio Rüdiger", "DEF", 86, 32, "Real Madrid"),
        ("Jonathan Tah", "DEF", 84, 29, "Bayern Munich"),
        ("David Raum", "DEF", 79, 27, "Leipzig"),
        ("Nico Schlotterbeck", "DEF", 81, 26, "Borussia Dortmund"),
        ("Manuel Neuer", "GK", 83, 39, "Bayern Munich"),
    ],
    "Curacao": [
        ("Leandro Bacuna", "MID", 73, 34, "Apoel Nicosia"),
        ("Tahith Chong", "MID", 75, 26, "Sheffield United"),
        ("Brian Brobbey", "FWD", 78, 23, "Ajax"),
        ("Juninho Bacuna", "MID", 74, 28, "Birmingham City"),
        ("Cuco Martina", "DEF", 71, 35, "Toulouse"),
        ("Eloy Room", "GK", 74, 36, "Columbus Crew"),
        ("Jurien Gaari", "DEF", 71, 28, "Helmond Sport"),
        ("Sherel Floranus", "DEF", 71, 27, "Heracles"),
        ("Roshon van Eijma", "DEF", 70, 25, "FC Eindhoven"),
        ("Rangelo Janga", "FWD", 71, 32, "Botev Plovdiv"),
        ("Kenji Gorré", "FWD", 71, 31, "PEC Zwolle"),
        ("Livano Comenencia", "DEF", 72, 21, "Juventus Next Gen"),
    ],
    "Ivory Coast": [
        ("Sébastien Haller", "FWD", 81, 31, "Utrecht"),
        ("Franck Kessié", "MID", 82, 28, "Al-Ahli"),
        ("Nicolas Pépé", "FWD", 79, 30, "Villarreal"),
        ("Simon Adingra", "FWD", 81, 23, "Sunderland"),
        ("Ibrahim Sangaré", "MID", 81, 27, "Nottingham Forest"),
        ("Jean-Michaël Seri", "MID", 78, 34, "Boavista"),
        ("Yan Diomandé", "FWD", 79, 18, "Leipzig"),
        ("Evan Ndicka", "DEF", 82, 26, "Roma"),
        ("Willy Boly", "DEF", 78, 34, "Nottingham Forest"),
        ("Ghislain Konan", "DEF", 76, 30, "Stade Reims"),
        ("Wilfried Singo", "DEF", 80, 24, "Monaco"),
        ("Yahia Fofana", "GK", 78, 25, "Angers"),
    ],
    "Ecuador": [
        ("Moisés Caicedo", "MID", 85, 24, "Chelsea"),
        ("Piero Hincapié", "DEF", 82, 23, "Arsenal"),
        ("Pervis Estupiñán", "DEF", 81, 27, "AC Milan"),
        ("Ángelo Preciado", "DEF", 76, 27, "Antwerp"),
        ("Willian Pacho", "DEF", 84, 24, "PSG"),
        ("Kendry Páez", "MID", 79, 18, "Chelsea"),
        ("Alan Minda", "FWD", 74, 22, "Cercle Brugge"),
        ("Enner Valencia", "FWD", 79, 36, "Inter Miami"),
        ("Jeremy Sarmiento", "FWD", 75, 23, "Burnley"),
        ("Gonzalo Plata", "FWD", 78, 25, "Flamengo"),
        ("José Cifuentes", "MID", 76, 26, "Cruzeiro"),
        ("Hernán Galíndez", "GK", 76, 38, "Huracán"),
    ],
    # ===== Group F =====
    "Netherlands": [
        ("Virgil van Dijk", "DEF", 87, 34, "Liverpool"),
        ("Frenkie de Jong", "MID", 85, 28, "Barcelona"),
        ("Memphis Depay", "FWD", 81, 31, "Corinthians"),
        ("Cody Gakpo", "FWD", 84, 26, "Liverpool"),
        ("Xavi Simons", "MID", 84, 22, "Leipzig"),
        ("Tijjani Reijnders", "MID", 85, 27, "Man City"),
        ("Denzel Dumfries", "DEF", 83, 29, "Inter"),
        ("Nathan Aké", "DEF", 81, 30, "Man City"),
        ("Matthijs de Ligt", "DEF", 83, 26, "Man United"),
        ("Jurriën Timber", "DEF", 82, 24, "Arsenal"),
        ("Donyell Malen", "FWD", 79, 26, "Aston Villa"),
        ("Bart Verbruggen", "GK", 81, 23, "Brighton"),
    ],
    "Japan": [
        ("Takefusa Kubo", "FWD", 84, 24, "Real Sociedad"),
        ("Kaoru Mitoma", "FWD", 84, 28, "Brighton"),
        ("Wataru Endō", "MID", 81, 32, "Liverpool"),
        ("Takumi Minamino", "FWD", 80, 30, "Monaco"),
        ("Daichi Kamada", "MID", 81, 29, "Crystal Palace"),
        ("Hidemasa Morita", "MID", 80, 30, "Sporting CP"),
        ("Daizen Maeda", "FWD", 78, 28, "Celtic"),
        ("Ko Itakura", "DEF", 80, 28, "Ajax"),
        ("Takehiro Tomiyasu", "DEF", 80, 27, "Arsenal"),
        ("Hiroki Itō", "DEF", 78, 26, "Bayern Munich"),
        ("Hiroki Sakai", "DEF", 76, 35, "Cerezo Osaka"),
        ("Zion Suzuki", "GK", 81, 23, "Parma"),
    ],
    "Sweden": [
        ("Alexander Isak", "FWD", 88, 26, "Liverpool"),
        ("Viktor Gyökeres", "FWD", 87, 27, "Arsenal"),
        ("Anthony Elanga", "FWD", 81, 23, "Newcastle"),
        ("Dejan Kulusevski", "MID", 83, 25, "Tottenham"),
        ("Lucas Bergvall", "MID", 80, 19, "Tottenham"),
        ("Mattias Svanberg", "MID", 77, 26, "Wolfsburg"),
        ("Jens Cajuste", "MID", 76, 26, "Ipswich Town"),
        ("Victor Lindelöf", "DEF", 80, 31, "Aston Villa"),
        ("Hjalmar Ekdal", "DEF", 76, 26, "Burnley"),
        ("Gabriel Gudmundsson", "DEF", 77, 26, "Leeds"),
        ("Daniel Svensson", "DEF", 75, 23, "Borussia Dortmund"),
        ("Robin Olsen", "GK", 79, 35, "Aston Villa"),
    ],
    "Tunisia": [
        ("Hannibal Mejbri", "MID", 77, 22, "Burnley"),
        ("Wahbi Khazri", "FWD", 76, 34, "Montpellier"),
        ("Anis Ben Slimane", "MID", 75, 24, "Sheffield United"),
        ("Ferjani Sassi", "MID", 76, 33, "Al-Duhail"),
        ("Naïm Sliti", "FWD", 76, 32, "Al-Ettifaq"),
        ("Issam Jebali", "FWD", 75, 33, "Helsingborgs"),
        ("Yassine Meriah", "DEF", 75, 32, "Esperance"),
        ("Dylan Bronn", "DEF", 76, 30, "Salernitana"),
        ("Mohamed Dräger", "DEF", 75, 29, "Luzern"),
        ("Ali Maaloul", "DEF", 76, 35, "Al-Ahly"),
        ("Aïssa Laïdouni", "MID", 77, 28, "Union Berlin"),
        ("Aymen Dahmen", "GK", 76, 28, "Sochaux"),
    ],
    # ===== Group G =====
    "Belgium": [
        ("Kevin De Bruyne", "MID", 87, 34, "Napoli"),
        ("Romelu Lukaku", "FWD", 83, 32, "Napoli"),
        ("Jérémy Doku", "FWD", 83, 23, "Man City"),
        ("Leandro Trossard", "FWD", 81, 30, "Arsenal"),
        ("Youri Tielemans", "MID", 82, 28, "Aston Villa"),
        ("Amadou Onana", "MID", 81, 24, "Aston Villa"),
        ("Charles De Ketelaere", "MID", 80, 24, "Atalanta"),
        ("Wout Faes", "DEF", 79, 27, "Leicester"),
        ("Arthur Theate", "DEF", 78, 25, "Eintracht Frankfurt"),
        ("Timothy Castagne", "DEF", 78, 29, "Fulham"),
        ("Maxim De Cuyper", "DEF", 78, 25, "Brighton"),
        ("Thibaut Courtois", "GK", 89, 33, "Real Madrid"),
    ],
    "Egypt": [
        ("Mohamed Salah", "FWD", 88, 33, "Liverpool"),
        ("Trezeguet", "FWD", 78, 31, "Trabzonspor"),
        ("Mohamed Elneny", "MID", 76, 33, "Al-Jazira"),
        ("Mahmoud Hassan", "MID", 76, 31, "Trabzonspor"),
        ("Mostafa Mohamed", "FWD", 77, 28, "Nantes"),
        ("Omar Marmoush", "FWD", 84, 26, "Man City"),
        ("Ramadan Sobhi", "MID", 75, 28, "Pyramids"),
        ("Mohamed Hamdy", "DEF", 73, 25, "Wolves"),
        ("Ahmed Hegazi", "DEF", 77, 34, "Ittihad Kalba"),
        ("Mohamed Abdelmonem", "DEF", 76, 26, "Al Ahly"),
        ("Mahmoud Hamdy", "DEF", 75, 30, "Zamalek"),
        ("Mohamed El-Shenawy", "GK", 78, 36, "Al Ahly"),
    ],
    "Iran": [
        ("Mehdi Taremi", "FWD", 82, 33, "Inter"),
        ("Sardar Azmoun", "FWD", 79, 30, "Shabab Al-Ahli"),
        ("Alireza Jahanbakhsh", "FWD", 78, 32, "Heerenveen"),
        ("Saman Ghoddos", "MID", 76, 32, "Brentford"),
        ("Saeid Ezatolahi", "MID", 75, 28, "Esteghlal"),
        ("Ahmad Nourollahi", "MID", 76, 32, "Persepolis"),
        ("Mohammad Mohebi", "FWD", 74, 26, "Rostov"),
        ("Mehdi Torabi", "MID", 75, 31, "Persepolis"),
        ("Shojae Khalilzadeh", "DEF", 76, 36, "Al-Ahli"),
        ("Sadegh Moharrami", "DEF", 75, 29, "Dinamo Zagreb"),
        ("Hossein Kanaanizadegan", "DEF", 76, 31, "Al-Ahli"),
        ("Alireza Beiranvand", "GK", 78, 33, "Persepolis"),
    ],
    "New Zealand": [
        ("Chris Wood", "FWD", 81, 34, "Nottingham Forest"),
        ("Marko Stamenić", "MID", 75, 23, "Olympiacos"),
        ("Liberato Cacace", "DEF", 76, 25, "Wolves"),
        ("Tyler Bindon", "DEF", 75, 20, "Reading"),
        ("Sarpreet Singh", "MID", 74, 27, "Yokohama F. Marinos"),
        ("Joe Bell", "MID", 75, 26, "Viking"),
        ("Matthew Garbett", "MID", 74, 23, "NAC Breda"),
        ("Elijah Just", "FWD", 73, 25, "Hibernian"),
        ("Kosta Barbarouses", "FWD", 73, 35, "Western Sydney"),
        ("Michael Boxall", "DEF", 75, 37, "Minnesota United"),
        ("Tim Payne", "DEF", 73, 31, "Auckland FC"),
        ("Alex Paulsen", "GK", 76, 23, "Bournemouth"),
    ],
    # ===== Group H =====
    "Spain": [
        ("Rodri", "MID", 90, 29, "Man City"),
        ("Pedri", "MID", 89, 23, "Barcelona"),
        ("Lamine Yamal", "FWD", 90, 18, "Barcelona"),
        ("Nico Williams", "FWD", 86, 23, "Barcelona"),
        ("Álvaro Morata", "FWD", 83, 33, "Galatasaray"),
        ("Fabián Ruiz", "MID", 85, 29, "PSG"),
        ("Dani Olmo", "MID", 84, 27, "Barcelona"),
        ("Aymeric Laporte", "DEF", 83, 31, "Athletic Bilbao"),
        ("Robin Le Normand", "DEF", 83, 29, "Atlético Madrid"),
        ("Marc Cucurella", "DEF", 81, 27, "Chelsea"),
        ("Dani Carvajal", "DEF", 84, 33, "Real Madrid"),
        ("Unai Simón", "GK", 85, 28, "Athletic Bilbao"),
    ],
    "Cape Verde": [
        ("Ryan Mendes", "FWD", 75, 35, "Sivasspor"),
        ("Garry Rodrigues", "FWD", 75, 35, "Pendikspor"),
        ("Jovane Cabral", "FWD", 75, 27, "Estrela Amadora"),
        ("Bebé", "FWD", 73, 35, "Hatayspor"),
        ("Stopira", "DEF", 74, 37, "Lugano"),
        ("Roberto Lopes", "DEF", 74, 33, "Shamrock Rovers"),
        ("Dylan Tavares", "DEF", 73, 31, "Annecy"),
        ("Jamiro Monteiro", "MID", 76, 32, "Boldklubben"),
        ("Logan Costa", "DEF", 75, 24, "Toulouse"),
        ("Steven Moreira", "DEF", 75, 31, "Columbus Crew"),
        ("Kenny Rocha Santos", "MID", 73, 30, "Salgueiros"),
        ("Vozinha", "GK", 74, 38, "Marítimo B"),
    ],
    "Saudi Arabia": [
        ("Salem Al-Dawsari", "MID", 81, 34, "Al-Hilal"),
        ("Saleh Al-Shehri", "FWD", 76, 31, "Al-Ittihad"),
        ("Firas Al-Buraikan", "FWD", 76, 25, "Al-Ahli"),
        ("Saud Abdulhamid", "DEF", 75, 26, "Roma"),
        ("Mohamed Kanno", "MID", 76, 31, "Al-Hilal"),
        ("Abdulelah Al-Malki", "MID", 75, 31, "Al-Hilal"),
        ("Nasser Al-Dawsari", "MID", 75, 26, "Al-Hilal"),
        ("Ali Al-Bulayhi", "DEF", 76, 36, "Al-Hilal"),
        ("Hassan Al-Tambakti", "DEF", 75, 26, "Al-Hilal"),
        ("Yasser Al-Shahrani", "DEF", 76, 33, "Al-Hilal"),
        ("Sultan Al-Ghannam", "DEF", 74, 31, "Al-Nassr"),
        ("Mohammed Al-Owais", "GK", 78, 34, "Al-Hilal"),
    ],
    "Uruguay": [
        ("Federico Valverde", "MID", 88, 27, "Real Madrid"),
        ("Darwin Núñez", "FWD", 82, 26, "Al Hilal"),
        ("Manuel Ugarte", "MID", 81, 24, "Man United"),
        ("Rodrigo Bentancur", "MID", 82, 28, "Tottenham"),
        ("Maximiliano Araújo", "FWD", 78, 26, "Sporting CP"),
        ("Facundo Pellistri", "FWD", 77, 24, "Panathinaikos"),
        ("Ronald Araújo", "DEF", 85, 26, "Barcelona"),
        ("José María Giménez", "DEF", 83, 30, "Atlético Madrid"),
        ("Mathías Olivera", "DEF", 78, 28, "Napoli"),
        ("Nahitan Nández", "DEF", 78, 30, "Al-Qadsiah"),
        ("Giorgian de Arrascaeta", "MID", 81, 31, "Flamengo"),
        ("Sergio Rochet", "GK", 78, 32, "Internacional"),
    ],
    # ===== Group I =====
    "France": [
        ("Kylian Mbappé", "FWD", 91, 27, "Real Madrid"),
        ("Antoine Griezmann", "FWD", 85, 34, "Atlético Madrid"),
        ("Ousmane Dembélé", "FWD", 87, 28, "PSG"),
        ("Aurélien Tchouaméni", "MID", 85, 25, "Real Madrid"),
        ("Eduardo Camavinga", "MID", 84, 23, "Real Madrid"),
        ("Adrien Rabiot", "MID", 83, 30, "AC Milan"),
        ("N'Golo Kanté", "MID", 81, 34, "Al Ittihad"),
        ("William Saliba", "DEF", 87, 24, "Arsenal"),
        ("Dayot Upamecano", "DEF", 84, 27, "Bayern Munich"),
        ("Theo Hernández", "DEF", 84, 28, "Al Hilal"),
        ("Jules Koundé", "DEF", 84, 27, "Barcelona"),
        ("Mike Maignan", "GK", 87, 30, "AC Milan"),
    ],
    "Senegal": [
        ("Sadio Mané", "FWD", 83, 33, "Al Nassr"),
        ("Kalidou Koulibaly", "DEF", 83, 34, "Al-Hilal"),
        ("Édouard Mendy", "GK", 82, 33, "Al-Ahli"),
        ("Ismaïla Sarr", "FWD", 81, 27, "Crystal Palace"),
        ("Boulaye Dia", "FWD", 79, 28, "Lazio"),
        ("Idrissa Gueye", "MID", 80, 36, "Everton"),
        ("Pape Matar Sarr", "MID", 80, 23, "Tottenham"),
        ("Nampalys Mendy", "MID", 76, 33, "Lens"),
        ("Iliman Ndiaye", "FWD", 79, 25, "Everton"),
        ("Krépin Diatta", "MID", 77, 26, "Monaco"),
        ("Abdou Diallo", "DEF", 78, 29, "Al-Arabi"),
        ("Habib Diallo", "FWD", 77, 30, "Damac"),
    ],
    "Iraq": [
        ("Ali Al-Hamadi", "FWD", 74, 23, "Ipswich Town"),
        ("Aymen Hussein", "FWD", 75, 29, "Al-Najaf"),
        ("Mohanad Ali", "FWD", 75, 25, "Al-Duhail"),
        ("Bashar Resan", "MID", 75, 28, "Al-Quwa Al-Jawiya"),
        ("Amir Al-Ammari", "MID", 74, 27, "Halmstads BK"),
        ("Ibrahim Bayesh", "MID", 73, 27, "Al-Najaf"),
        ("Zidane Iqbal", "MID", 76, 22, "Utrecht"),
        ("Frans Putros", "DEF", 73, 32, "Mjällby"),
        ("Manaf Younis", "DEF", 73, 29, "Al-Naft"),
        ("Merchas Doski", "DEF", 73, 30, "Al-Talaba"),
        ("Akam Hashim", "DEF", 73, 25, "Erbil"),
        ("Jalal Hassan", "GK", 74, 31, "Al-Quwa Al-Jawiya"),
    ],
    "Norway": [
        ("Erling Haaland", "FWD", 91, 25, "Man City"),
        ("Martin Ødegaard", "MID", 87, 27, "Arsenal"),
        ("Antonio Nusa", "FWD", 80, 20, "Leipzig"),
        ("Oscar Bobb", "MID", 79, 22, "Man City"),
        ("Sander Berge", "MID", 80, 27, "Fulham"),
        ("Patrick Berg", "MID", 76, 28, "Bodø/Glimt"),
        ("Fredrik Aursnes", "MID", 79, 30, "Benfica"),
        ("Kristoffer Ajer", "DEF", 78, 27, "Brentford"),
        ("Leo Skiri Østigård", "DEF", 76, 26, "Rennes"),
        ("Birger Meling", "DEF", 76, 31, "Rennes"),
        ("Julian Ryerson", "DEF", 78, 28, "Borussia Dortmund"),
        ("Ørjan Nyland", "GK", 77, 35, "Sevilla"),
    ],
    # ===== Group J =====
    "Argentina": [
        ("Lionel Messi", "FWD", 89, 38, "Inter Miami"),
        ("Lautaro Martínez", "FWD", 87, 28, "Inter"),
        ("Julián Álvarez", "FWD", 87, 26, "Atlético Madrid"),
        ("Enzo Fernández", "MID", 86, 25, "Chelsea"),
        ("Alexis Mac Allister", "MID", 86, 27, "Liverpool"),
        ("Rodrigo De Paul", "MID", 83, 31, "Atlético Madrid"),
        ("Cristian Romero", "DEF", 86, 27, "Tottenham"),
        ("Lisandro Martínez", "DEF", 84, 28, "Man United"),
        ("Nicolás Otamendi", "DEF", 79, 37, "Benfica"),
        ("Nahuel Molina", "DEF", 80, 27, "Atlético Madrid"),
        ("Nicolás Tagliafico", "DEF", 79, 33, "Lyon"),
        ("Emiliano Martínez", "GK", 87, 33, "Aston Villa"),
    ],
    "Algeria": [
        ("Riyad Mahrez", "FWD", 84, 34, "Al-Ahli"),
        ("Ismaël Bennacer", "MID", 81, 28, "AC Milan"),
        ("Saïd Benrahma", "FWD", 80, 30, "Lyon"),
        ("Houssem Aouar", "MID", 79, 27, "Al-Ittihad"),
        ("Baghdad Bounedjah", "FWD", 77, 33, "Al-Sadd"),
        ("Yacine Brahimi", "MID", 77, 35, "Al-Gharafa"),
        ("Aïssa Mandi", "DEF", 78, 33, "Lille"),
        ("Ramy Bensebaini", "DEF", 80, 30, "Borussia Dortmund"),
        ("Mohamed Farès", "DEF", 76, 29, "Panathinaikos"),
        ("Youcef Atal", "DEF", 77, 29, "Al-Sadd"),
        ("Sofiane Feghouli", "MID", 77, 35, "Fatih Karagümrük"),
        ("Raïs M'Bolhi", "GK", 76, 39, "ES Sétif"),
    ],
    "Austria": [
        ("David Alaba", "DEF", 82, 33, "Real Madrid"),
        ("Marcel Sabitzer", "MID", 82, 31, "Borussia Dortmund"),
        ("Konrad Laimer", "MID", 81, 28, "Bayern Munich"),
        ("Christoph Baumgartner", "MID", 80, 26, "Leipzig"),
        ("Marko Arnautović", "FWD", 79, 36, "Red Star"),
        ("Michael Gregoritsch", "FWD", 78, 31, "Brøndby"),
        ("Romano Schmid", "MID", 77, 25, "Werder Bremen"),
        ("Maximilian Wöber", "DEF", 78, 27, "Borussia Mönchengladbach"),
        ("Stefan Posch", "DEF", 77, 28, "Como"),
        ("Phillipp Mwene", "DEF", 75, 31, "PSV"),
        ("Patrick Wimmer", "MID", 76, 24, "Wolfsburg"),
        ("Patrick Pentz", "GK", 76, 28, "Brøndby"),
    ],
    "Jordan": [
        ("Mousa Al-Tamari", "FWD", 79, 28, "Montpellier"),
        ("Yazan Al-Naimat", "FWD", 75, 26, "Al-Ahli SC"),
        ("Mahmoud Al-Mardi", "MID", 74, 28, "Al-Ahli SC"),
        ("Nizar Al-Rashdan", "MID", 75, 26, "Al-Faisaly"),
        ("Noor Al-Rawabdeh", "MID", 73, 30, "Al-Faisaly"),
        ("Ehsan Haddad", "DEF", 74, 26, "Al-Wehdat"),
        ("Yazan Al-Arab", "DEF", 75, 27, "Al-Wehdat"),
        ("Salem Al-Ajalin", "DEF", 73, 28, "Al-Ramtha"),
        ("Bara' Marei", "DEF", 73, 25, "Al-Ramtha"),
        ("Ali Olwan", "FWD", 73, 28, "Al-Ahli SC"),
        ("Mahmoud Eid", "MID", 73, 25, "Häcken"),
        ("Yazeed Abulaila", "GK", 75, 35, "Al-Hussein"),
    ],
    # ===== Group K =====
    "Portugal": [
        ("Cristiano Ronaldo", "FWD", 84, 41, "Al Nassr"),
        ("Bruno Fernandes", "MID", 86, 31, "Man United"),
        ("Bernardo Silva", "MID", 86, 31, "Man City"),
        ("Vitinha", "MID", 88, 25, "PSG"),
        ("Rafael Leão", "FWD", 84, 26, "AC Milan"),
        ("Diogo Jota", "FWD", 83, 28, "Liverpool"),
        ("João Neves", "MID", 84, 21, "PSG"),
        ("Rúben Dias", "DEF", 88, 28, "Man City"),
        ("Nuno Mendes", "DEF", 85, 23, "PSG"),
        ("João Cancelo", "DEF", 83, 31, "Al Hilal"),
        ("Pepe", "DEF", 78, 42, "FC Porto"),
        ("Diogo Costa", "GK", 85, 26, "FC Porto"),
    ],
    "DR Congo": [
        ("Cédric Bakambu", "FWD", 78, 34, "Real Betis"),
        ("Yoane Wissa", "FWD", 80, 29, "Newcastle"),
        ("Silas Katompa", "FWD", 78, 27, "Red Bull Salzburg"),
        ("Théo Bongonda", "FWD", 77, 30, "Al-Shabab"),
        ("Cédric Bakambu", "FWD", 78, 34, "Real Betis"),
        ("Samuel Moutoussamy", "MID", 75, 29, "Lorient"),
        ("Charles Pickel", "MID", 76, 28, "Cremonese"),
        ("Chancel Mbemba", "DEF", 80, 31, "Lille"),
        ("Arthur Masuaku", "DEF", 76, 32, "Sunderland"),
        ("Axel Tuanzebe", "DEF", 75, 28, "Burnley"),
        ("Gédéon Kalulu", "DEF", 75, 28, "Lorient"),
        ("Lionel Mpasi", "GK", 76, 31, "Rodez"),
    ],
    "Uzbekistan": [
        ("Eldor Shomurodov", "FWD", 78, 30, "Roma"),
        ("Abbosbek Fayzullaev", "MID", 77, 22, "CSKA Moscow"),
        ("Khojimat Erkinov", "MID", 75, 26, "Andijon"),
        ("Igor Sergeev", "FWD", 74, 32, "Sheriff Tiraspol"),
        ("Jaloliddin Masharipov", "MID", 76, 32, "Pakhtakor"),
        ("Otabek Shukurov", "MID", 75, 29, "Sharjah"),
        ("Sherzod Azamov", "FWD", 74, 26, "Pakhtakor"),
        ("Abdukodir Khusanov", "DEF", 80, 21, "Man City"),
        ("Rustamjon Ashurmatov", "DEF", 75, 29, "Gangwon"),
        ("Sherzod Nasrullaev", "DEF", 73, 25, "Pakhtakor"),
        ("Farrukh Sayfiev", "DEF", 73, 30, "Pakhtakor"),
        ("Utkir Yusupov", "GK", 76, 29, "Pakhtakor"),
    ],
    "Colombia": [
        ("Luis Díaz", "FWD", 87, 28, "Bayern Munich"),
        ("James Rodríguez", "MID", 81, 34, "Club León"),
        ("Jhon Durán", "FWD", 79, 22, "Fenerbahçe"),
        ("Jhon Arias", "FWD", 81, 28, "Wolves"),
        ("Richard Ríos", "MID", 80, 25, "Benfica"),
        ("Mateus Uribe", "MID", 79, 34, "Al Sadd"),
        ("Jefferson Lerma", "MID", 80, 31, "Crystal Palace"),
        ("Davinson Sánchez", "DEF", 80, 29, "Galatasaray"),
        ("Yerry Mina", "DEF", 78, 31, "Cagliari"),
        ("Daniel Muñoz", "DEF", 80, 29, "Crystal Palace"),
        ("Johan Mojica", "DEF", 77, 33, "Mallorca"),
        ("Camilo Vargas", "GK", 78, 36, "Atlas"),
    ],
    # ===== Group L =====
    "England": [
        ("Harry Kane", "FWD", 89, 32, "Bayern Munich"),
        ("Jude Bellingham", "MID", 87, 22, "Real Madrid"),
        ("Bukayo Saka", "FWD", 87, 24, "Arsenal"),
        ("Phil Foden", "MID", 86, 25, "Man City"),
        ("Cole Palmer", "MID", 87, 23, "Chelsea"),
        ("Declan Rice", "MID", 87, 27, "Arsenal"),
        ("Marcus Rashford", "FWD", 82, 28, "Aston Villa"),
        ("John Stones", "DEF", 84, 31, "Man City"),
        ("Marc Guéhi", "DEF", 82, 25, "Crystal Palace"),
        ("Kyle Walker", "DEF", 81, 35, "Burnley"),
        ("Luke Shaw", "DEF", 80, 30, "Man United"),
        ("Jordan Pickford", "GK", 84, 31, "Everton"),
    ],
    "Croatia": [
        ("Luka Modrić", "MID", 84, 40, "AC Milan"),
        ("Mateo Kovačić", "MID", 82, 31, "Man City"),
        ("Marcelo Brozović", "MID", 80, 33, "Al Nassr"),
        ("Andrej Kramarić", "FWD", 79, 34, "Hoffenheim"),
        ("Bruno Petković", "FWD", 76, 31, "Dinamo Zagreb"),
        ("Ante Budimir", "FWD", 78, 34, "Osasuna"),
        ("Joško Gvardiol", "DEF", 86, 23, "Man City"),
        ("Joško Šutalo", "DEF", 78, 25, "Ajax"),
        ("Borna Sosa", "DEF", 77, 27, "Ajax"),
        ("Josip Stanišić", "DEF", 78, 25, "Bayern Munich"),
        ("Luka Sučić", "MID", 79, 23, "Real Sociedad"),
        ("Dominik Livaković", "GK", 81, 30, "Girona"),
    ],
    "Ghana": [
        ("Mohammed Kudus", "MID", 85, 25, "Tottenham"),
        ("Antoine Semenyo", "FWD", 82, 25, "Bournemouth"),
        ("Inaki Williams", "FWD", 82, 31, "Athletic Bilbao"),
        ("Jordan Ayew", "FWD", 78, 34, "Leicester"),
        ("Thomas Partey", "MID", 83, 32, "Villarreal"),
        ("Kamaldeen Sulemana", "FWD", 79, 23, "Atalanta"),
        ("Salis Abdul Samed", "MID", 78, 25, "Lens"),
        ("Mohammed Salisu", "DEF", 80, 26, "Monaco"),
        ("Alidu Seidu", "DEF", 76, 25, "Rennes"),
        ("Daniel Amartey", "DEF", 77, 30, "Besiktas"),
        ("Tariq Lamptey", "DEF", 77, 25, "Brighton"),
        ("Lawrence Ati-Zigi", "GK", 76, 28, "St. Gallen"),
    ],
    "Panama": [
        ("Adalberto Carrasquilla", "MID", 76, 27, "Pumas UNAM"),
        ("Aníbal Godoy", "MID", 76, 35, "San Jose"),
        ("Edgar Bárcenas", "MID", 75, 32, "Mazatlán"),
        ("Cecilio Waterman", "FWD", 75, 34, "Coquimbo Unido"),
        ("José Fajardo", "FWD", 74, 29, "Tauro"),
        ("Ismael Díaz", "FWD", 76, 28, "León"),
        ("Michael Murillo", "DEF", 77, 30, "Olympique Marseille"),
        ("Fidel Escobar", "DEF", 75, 30, "Real Salt Lake"),
        ("Edson Samaniego", "DEF", 73, 27, "Cádiz"),
        ("Eric Davis", "DEF", 75, 34, "Aris Limassol"),
        ("César Yanis", "FWD", 73, 26, "Tauro"),
        ("Orlando Mosquera", "GK", 76, 35, "Real Hope"),
    ],
}
